# This is the configuration file for Lithium.
#
# You can find information on editing this file and all the available options here:
# https://github.com/CaffeineMC/lithium-fabric/wiki/Configuration-File
#
# Lithium Optimization - Performance Tuning
lithium.mixin.alloc.compacted_slab_state=true
lithium.mixin.chunk.palette=true
lithium.mixin.entity.collisions.shapes=true
lithium.mixin.util.entity_chunk_lookup=true
lithium.mixin.util.block_palette=true
lithium.mixin.world.block_entity_ticking.sleeping=true
lithium.mixin.world.chunk_access=true
