#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 14 10:13:38 UYT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1.zip
